name: Build Spring Boot App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Dar permisos a Maven
        run: chmod +x mvnw

      - name: Compilar proyecto (sin tests)
        run: ./mvnw clean install -DskipTests
